.TH "example" 3 "Sat Feb 5 2022" "Zumpy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
example
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBarr\fP = \fBarray\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "example\&.arr = \fBarray\fP()"

.PP
Definition at line \fB4\fP of file \fBexample\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zumpy from the source code\&.
