.TH "zumpy" 3 "Sat Feb 5 2022" "Zumpy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zumpy
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBarray\fP"
.br
.RI "Array Module A simple array class that handles arbitrary dimensions for integer and float types\&. "
.ti -1c
.RI "class \fBarray_wrapper\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zumpy from the source code\&.
