.TH "src/python/zumpy.py" 3 "Sat Feb 5 2022" "Zumpy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/python/zumpy.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBzumpy\&.array_wrapper\fP"
.br
.ti -1c
.RI "class \fBzumpy\&.array\fP"
.br
.RI "Array Module A simple array class that handles arbitrary dimensions for integer and float types\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBzumpy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zumpy from the source code\&.
