.TH "zumpy.array_wrapper" 3 "Sat Feb 5 2022" "Zumpy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zumpy.array_wrapper
.SH SYNOPSIS
.br
.PP
.PP
Inherits Structure\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBargtypes\fP"
.br
.ti -1c
.RI "\fBrestype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Zumpy from the source code\&.
