.TH "array" 3 "Mon Jan 31 2022" "Zumpy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
array
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zumpy\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "size_t * \fBarr_shape\fP"
.br
.ti -1c
.RI "size_t \fBshape_size\fP"
.br
.ti -1c
.RI "size_t \fBtype_size\fP"
.br
.ti -1c
.RI "size_t \fBtotal_size\fP"
.br
.ti -1c
.RI "\fBtype\fP \fBdtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBzumpy\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "size_t* arr_shape"

.PP
Definition at line \fB16\fP of file \fBzumpy\&.h\fP\&.
.SS "void* data"

.PP
Definition at line \fB15\fP of file \fBzumpy\&.h\fP\&.
.SS "\fBtype\fP dtype"

.PP
Definition at line \fB20\fP of file \fBzumpy\&.h\fP\&.
.SS "size_t shape_size"

.PP
Definition at line \fB17\fP of file \fBzumpy\&.h\fP\&.
.SS "size_t total_size"

.PP
Definition at line \fB19\fP of file \fBzumpy\&.h\fP\&.
.SS "size_t type_size"

.PP
Definition at line \fB18\fP of file \fBzumpy\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zumpy from the source code\&.
