.TH "src/c/main.c" 3 "Mon Jan 31 2022" "Zumpy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/c/main.c
.SH SYNOPSIS
.br
.PP
\fC#include 'include/zumpy\&.h'\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBfilter\fP (void *value)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool filter (void * value)"

.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Zumpy from the source code\&.
